### ISSUE TITLE
Feature: User can search for cards

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/card-thief#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for cards

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to search for any Yugioh card by name 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/192331224-a3ffd9f0-9118-4abe-a800-0025036d47bf.png)
![image](https://user-images.githubusercontent.com/109745413/192331285-a4d031af-8ba5-4933-84a9-fe8f077bf78f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a `<div>`  for the background, with a dark gray background color
- [x] Create a `<div>`  for the header
- [x] Add in a title
- [x] Create a search bar and button
- [x] Create a div for storing search content with a light background color
- [x] Create a function for checking the window size and show the proper search bar
- [x] Create a function to truncate the card texts
- [x] Create a new XMLHttpRequest object for card information
- [x] Use this request to extract card name, text, and price
- [x] Create an object for getting search result
- [x] Add an event listener for detecting search
- [x] Create search cards based on search text
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
