### ISSUE TITLE
Feature: User can remove a card from their deck

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/card-thief#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove a card from their deck

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a user added a card to their deck by accident, they can remove it

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/193317280-2023af8e-db71-4621-8161-7b3954e99304.png)
![image](https://user-images.githubusercontent.com/109745413/193317311-192f38f6-885c-4d4c-8134-005aa58c2100.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add in subtract button
- [x] Add in event listener function for subtract button
- [x] Remove the card data from deckData object
- [x] Remove the element from the document
- [x] Update value of the deck
- [x] Hide the button when not in deck
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
