### ISSUE TITLE
Feature: User can view a title page of the app

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/card-thief#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a title page of the app

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view a title page of the app 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/193317452-0c299ffa-8aa5-46b2-92a1-fd6a427c8994.png)
![image](https://user-images.githubusercontent.com/109745413/193317469-56d80114-4955-404f-a991-ecb380231473.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a modal with a custom background
- [x] Create a button and a title
- [x] Add an event listener to hide the modal
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
