### ISSUE TITLE
Feature: User can view details for a single card

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/card-thief#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details for a single card

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks on a card from their search list, they will be able to see the full card details

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/192332363-27308298-46ee-4e3c-aa6a-45859dc48b4c.png)
![image](https://user-images.githubusercontent.com/109745413/192332421-991f99c9-baf8-49b5-b4b8-7b461b61683d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a container div to store the single view card
- [x] Enlarge the div with card when the view is in window
- [x] Add in margins between text blocks
- [x] Add in image divs to store price logos
- [x] Make the divs fit a certain size
- [x] Add in a price for each site
- [x] Create a function to detect a click and update card information
- [x] Create a function to search for exact card names
- [x] Create an object to store card information 
- [x] Create query selector for all card information that needs updating
- [x] Hide the search view when clicked and switch to single card view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
