### ISSUE TITLE
Feature: User can add a card to their deck

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/card-thief#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a card to their deck

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to store favorite cards to a deck

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/192333405-aa3a3226-0f9d-4743-9947-f52bf2b8a4df.png)
![image](https://user-images.githubusercontent.com/109745413/192333439-2d5d240e-3303-41fe-9763-d49f0088de7f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add in a blue button image inside of my title element
- [x] Create a data object that stores the card name and the previous card search name
- [x] Create an event listener to detect the button image being clicked and pushes the card name into the data object
- [x] Update the display to the search view before detailed view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
