### ISSUE TITLE
Feature: User can view their deck

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/card-thief#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their deck

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to view the cards they have saved

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/192333715-fad889f4-f4d7-4320-9100-4b4cedca5246.png)
![image](https://user-images.githubusercontent.com/109745413/192333741-5d029334-6656-4cf5-9f2b-a83aca2cf235.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a container for storing deck images
- [x] Create a deck container for storing the cards from the deck
- [x] Use flexbox to organize images
- [x] Update header. Add in deck and search options
- [x] Create a function to add cards into the deck
- [x] Update event listener to hide deck when searching
- [x] Update event listener to hide search bar when viewing deck
- [x] Update event listener to show cards when clicked
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
