### ISSUE TITLE
Feature: Users can view the total cost of their deck

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/card-thief#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view the total cost of their deck

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to view the total cost of their deck

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109745413/192333805-d90ce0a5-4373-45c2-99be-57b2cfee05c1.png)
![image](https://user-images.githubusercontent.com/109745413/192333836-19e6d43d-c2b0-4732-ab1b-9c5377925de2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a div to store the card price
- [x] Update deckData object to store card price information
- [x] Create a function that calculates the card prices for the deck based off of the lowest cost of card that is not 0.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
